// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb621jSoSahPRT7wrt13ey1C80a630ewk',
    appId: '1:913360047516:web:a450f2577f7a7cbb5c4c59',
    messagingSenderId: '913360047516',
    projectId: 'tradelogic-b60f0',
    authDomain: 'tradelogic-b60f0.firebaseapp.com',
    databaseURL: 'https://tradelogic-b60f0-default-rtdb.firebaseio.com',
    storageBucket: 'tradelogic-b60f0.firebasestorage.app',
    measurementId: 'G-LVMC0RMKKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_vsMWKfDN3w7hPnp4eshJ0YfEvA0870o',
    appId: '1:913360047516:android:f506c050e10a9da75c4c59',
    messagingSenderId: '913360047516',
    projectId: 'tradelogic-b60f0',
    databaseURL: 'https://tradelogic-b60f0-default-rtdb.firebaseio.com',
    storageBucket: 'tradelogic-b60f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlrsQvQW4G_aIszk0BEEuO-M1dxVgv-Ws',
    appId: '1:913360047516:ios:59ddb37261e27e855c4c59',
    messagingSenderId: '913360047516',
    projectId: 'tradelogic-b60f0',
    databaseURL: 'https://tradelogic-b60f0-default-rtdb.firebaseio.com',
    storageBucket: 'tradelogic-b60f0.firebasestorage.app',
    iosBundleId: 'com.example.tradelogic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlrsQvQW4G_aIszk0BEEuO-M1dxVgv-Ws',
    appId: '1:913360047516:ios:59ddb37261e27e855c4c59',
    messagingSenderId: '913360047516',
    projectId: 'tradelogic-b60f0',
    databaseURL: 'https://tradelogic-b60f0-default-rtdb.firebaseio.com',
    storageBucket: 'tradelogic-b60f0.firebasestorage.app',
    iosBundleId: 'com.example.tradelogic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb621jSoSahPRT7wrt13ey1C80a630ewk',
    appId: '1:913360047516:web:920e64adea9498c05c4c59',
    messagingSenderId: '913360047516',
    projectId: 'tradelogic-b60f0',
    authDomain: 'tradelogic-b60f0.firebaseapp.com',
    databaseURL: 'https://tradelogic-b60f0-default-rtdb.firebaseio.com',
    storageBucket: 'tradelogic-b60f0.firebasestorage.app',
    measurementId: 'G-M3F5FS0HQ5',
  );
}
